import Head from "next/head";
import { useEffect, useState } from "react";
import Nav from "../components/Nav";
import Projects from "./projects";
import Skills from "./Skills";
import Main from "./Main";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

useEffect(() => {
  // window.localStorage.clear()
  const theme = JSON.parse(window.localStorage.getItem('darkMode'))
  if(theme !== null){
    setDarkMode(theme)
  }
}, [])


  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Richard Wave Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white dark:bg-gray-900 ">
        <Nav setDarkMode={setDarkMode} darkMode={darkMode} />
        <Main />
        <Skills />
        <Projects />
      </main>
    </div>
  );
}
